# Generated by Django 4.0.1 on 2022-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bookId',
            field=models.BigIntegerField(default=1),
        ),
    ]
