# Generated by Django 4.0.1 on 2022-08-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bookId',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
